name: simple_auth_flutter
description: Simple Auth is the simplest way to authenticate your users/apis. This plugin will securely store tokens/credentials as well as automatically present login UI when needed.
version: 1.0.6
author: James Clancey <james.clancey@gmail.com>
homepage: https://github.com/clancey/simple_auth

environment:
    sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_auth: ^1.0.6
  flutter_secure_storage:
    
flutter:
  plugin:
    androidPackage: clancey.simpleauth.simpleauthflutter
    pluginClass: SimpleAuthFlutterPlugin
